---
title: "EC349-Assignment"
author: "Travis Tan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plans

* First, I have decided to first construct a model out of Ridge regression to help identify which variables might have the strongest explanatory power. If some predictors truly have outsized explanatory power, I will then perform LASSO regression to perform feature selection. 
  * I would examine which model performed better, if some predictors have disproportionate explanatory power, the LASSO should perform better than the ridge.
  
* If there isn't, I would then examine random forests as a possible feasible alternative.
  * This could be seen as a classification problem- depending on conditions, businesses might get above a threshold of stars as stars are given in .5 increments.


### Linear models

* I will first find trends between features to see how stars are given: Would more active users give more or fewer stars on average?
  * To do this, I would have to find the user and business features that could predict stars given. So 2 models first:
    * Stars given according to user features: $$stars = \sum_{j=1}^{u} \beta_j * user feature_j  $$
    * Stars given according to business features: $$stars = \sum_{k=1}^{b} \beta_k * business feature_k  $$
    * Taking the two: $$stars = \sum_{j=1}^{u} \beta_j * user feature_j + \sum_{k=1}^{b} \beta_k * business feature_k$$  
    This will be my starting model for ridge regression.

Remember that big businesses are more likely to have available data and not a whole bunch of NA's. This means I may be better off
creating 2 models, one model for big businesses and one for small.  

I first split training data set on user data into 75/25.

### Variable Selection
Before formally choosing a model, understanding the variables is crucial. To predict the stars a business receives from a user requires user and business features, starting with business data:  
* city, state, latitude, longitude: location features  
* review count  
* stars  
* engagement: measured by number of attributes a business filled, this indicates how much they value 
* category count? Shows 
* business category  
* opening hour availability?  
 
For user data:  
* Could consider making a variable for each elite year and checking whether that improves performance, just a thought.  
* Keep all compliments separate, and include total_compliments  
* 
  
What could determine how many stars a business receives from a user?  
* Business features as above, but also how many checkins a business may receive. Some business categories would receive more than others?  
* User features as above  
* Review positivity by user? Like whether a review is positive, useful, funny, cool etc. This requires sentiment analysis.  
* Tip data, same as review positivity.  
*   

Also important to remember to be mindful of outliers like hyper-active users who might rate differently from the average yelp user.

### Possible improvements
Due to time constraint, I couldn't try these methods but I do think they could improve the model:  
* Doing sentiment analysis on tip and review data
* Using unsupervised machine learning to sort business categories







